import { Outfit } from "next/font/google";
import "./globals.css";
import { Providers } from "@/Components/Providers";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body
        className={`${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </Providers>

    </html>
    
  );
}
